version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb_service
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express_vue
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb

  express-app:
    build: ./backend
    container_name: express-app_vue
    depends_on:
      - mongodb
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - JWT_SECRET=your_jwt_secret_key
      - MONGODB_URL=mongodb://admin:admin@mongodb:27017/mongoDB
    volumes:
      - ./backend:/app
    command: ["npm", "start"]

volumes:
  mongo-data: